# Generated by Django 5.2.6 on 2025-09-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=7,
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("color", models.CharField(blank=True, max_length=7)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "indexes": [
                    models.Index(
                        fields=["type", "parent"], name="categories__type_fcec48_idx"
                    )
                ],
                "unique_together": {("name", "parent", "type")},
            },
        ),
    ]
