# Generated by Django 5.2.6 on 2025-09-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
    ]
